@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant ":VoteAPI" as vote1

activate User

User -> vote1: GET/votes/
vote1 --> User: List<votes>

@enduml