@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant ":VoteController" as Ctrl
participant ":VoteService" as Service
participant ":VoteRepository" as Rep

activate User

User -> Ctrl: GET/votes/
Ctrl -> Service: getAllVotes()
Service -> Rep: findAllVotes()
Rep --> Service: List<votes>
Service --> Ctrl: List<votes>

Ctrl --> User: List<votes>

@enduml