@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant ":VoteAPI" as vote1
participant ":ReviewsApi" as Rev

activate User

User -> vote1: POST/votes/updateVote
vote1 -> Rev: GET/8081/reviews/status/{reviewId}
Rev --> vote1 : APPROVED
vote1 --> User: vote

@enduml