@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant ":VoteAPI" as vote1
participant ":Vote" as vote2

activate User

User -> vote1: GET/votes/{reviewId}
vote1 -> vote2: GET/8085/votes/{reviewId}
vote2 --> vote1: int
vote1 --> User: int

@enduml